project:
  type: website
  render:
    - "*.qmd"
    - "case-study/boiarsky/*.ipynb"
  resources:
    - "case-study/boiarsky/*.py"
    - "case-study/boiarsky/*.R"
    - "case-study/boiarsky/*.md"
    - "case-study/boiarsky/downloads/*.ipynb"

website:
  title: "SimiC-Suite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simicpipeline.qmd
        text: SimiCPipeline
      - href: simicviz.qmd
        text: SimiCviz
      - href: case-study.qmd
        text: Case Study
      - href: citation.qmd
        text: Citation
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "SimiC-Suite"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

execute:
  enabled: false
  freeze: true
