project:
  type: website
  render:
    - "*.qmd"
    - "tutorials/simicpipeline/*.ipynb"
  resources:
    - "tutorials/simicpipeline/*.ipynb"
    - "tutorials/simicpipeline/downloads/*.ipynb"
    - "tutorials/simicpipeline/*.py"
    - "tutorials/simicviz/SimiCviz.html"
    - "tutorials/simicviz/SimiCviz.Rmd"
    - "tutorials/simicviz/SimiCviz.R"

website:
  title: "SimiC-Suite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simicpipeline.qmd
        text: SimiCPipeline
      - href: simicviz.qmd
        text: SimiCviz
      - href: citation.qmd
        text: Citation
  page-footer:
    left: "SimiC-Suite"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

execute:
  enabled: false
  freeze: true
